ALTER DATABASE mackenzie SET datestyle TO "ISO, MDY";
ALTER DATABASE mackenzie_dev SET datestyle TO "ISO, MDY";

CREATE SCHEMA sonde;
CREATE SCHEMA dgt;
CREATE SCHEMA pmd;
CREATE SCHEMA grab;
CREATE SCHEMA app;
CREATE SCHEMA lookups;
